models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Albaran(db.Model):
    idAlbaran = db.Column(db.Integer, primary_key=True, autoincrement=True)
    fechaRecepcion = db.Column(db.Date, nullable=False)
    proveedor = db.Column(db.String(100), nullable=False)
    productos = db.relationship('AlbaranProductos', backref='albaran', lazy=True)

class AlbaranProductos(db.Model):
    albaran_id = db.Column(db.Integer, db.ForeignKey('albaran.idAlbaran'), primary_key=True)
    producto_id = db.Column(db.Integer, db.ForeignKey('productos.idProducto'), primary_key=True)
    cantidad = db.Column(db.Integer, nullable=False)

class Productos(db.Model):
    idProducto = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nameProduct = db.Column(db.String(80), unique=True, nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=True)
    stock = db.Column(db.Integer, nullable=False)
    state = db.Column(db.Boolean, nullable=False)
    albaranes = db.relationship('AlbaranProductos', backref='productos', lazy=True)
    facturas = db.relationship('FacturasProductos', backref='productos', lazy=True)

class FacturasProductos(db.Model):
    idFactura = db.Column(db.Integer, db.ForeignKey('facturas.idFactura'), primary_key=True)
    idProducto = db.Column(db.Integer, db.ForeignKey('productos.idProducto'), primary_key=True)
    cantidad = db.Column(db.Integer, nullable=False)
    preu = db.Column(db.Numeric(10, 2), nullable=False)

class Facturas(db.Model):
    idFactura = db.Column(db.Integer, primary_key=True, autoincrement=True)
    fecha = db.Column(db.Date, nullable=False)
    productos = db.relationship('FacturasProductos', backref='Facturas', lazy=True)

app.py
from flask import Flask
from routes import main
from models import db
from flask_wtf.csrf import CSRFProtect

#Creamos la app
app = Flask(__name__)
csrf = CSRFProtect(app)

app.config['SECRET_KEY'] = 'una-clave-secreta-muy-segura'

#Configuramos la app
app.config.from_object('config.DevConfig')

#Registramos las rutas
app.register_blueprint(main)

#Inicializamos el ORM
db.init_app(app)

#Creamos la base de datos
with app.app_context():
    db.create_all()

routes.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from models import Productos, Albaran, Facturas, db, AlbaranProductos, FacturasProductos
from formularios import AlbaranForm, FacturasForm
from datetime import datetime

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/productos')
def productos():
    productos = Productos.query.all()
    return render_template('productos.html', productos=productos)

@main.route('/producto/<int:idProducto>', methods=['GET'])
def producto(idProducto):
    producto = Productos.query.get_or_404(idProducto)
    return render_template('producto.html', producto=producto)

@main.route('/ver-mas/<int:idProducto>', methods=['GET'])
def ver_mas(idProducto):
    return redirect(url_for('main.producto', idProducto=idProducto))

@main.route('/albaranes', methods=['GET', 'POST'])
def albaran():
    form = AlbaranForm()
    if request.method == 'POST' and form.validate_on_submit():
        albaran = Albaran()
        albaran.fechaRecepcion = datetime.now()
        albaran.proveedor = form.proveedor.data  # Obtener el proveedor del formulario

        db.session.add(albaran)
        db.session.commit()

        for i in range(5):  # Iterar sobre los 5 productos
            producto_nombre = request.form.get(f'producto{i}')
            cantidad = request.form.get(f'cantidad{i}', type=int)

            if producto_nombre and cantidad:
                producto = Productos.query.filter_by(nameProduct=producto_nombre).first()
                if producto:
                    producto.stock += cantidad
                    db.session.commit()

                    albaran_producto = AlbaranProductos(albaran_id=albaran.idAlbaran, producto_id=producto.idProducto, cantidad=cantidad)
                    db.session.add(albaran_producto)
                else:
                    new_product = Productos(nameProduct=producto_nombre, stock=cantidad, price=None, state=True)
                    db.session.add(new_product)
                    db.session.commit()

                    albaran_producto = AlbaranProductos(albaran_id=albaran.idAlbaran, producto_id=new_product.idProducto, cantidad=cantidad)
                    db.session.add(albaran_producto)
        db.session.commit()

        print('Albarán creado con éxito y guardado en la base de datos!')
        return redirect(url_for('main.productos'))

    return render_template('albaran.html', form=form)

@main.route('/facturas', methods=['GET', 'POST'])
def facturas():
    form = FacturasForm()
    if request.method == 'POST' and form.validate_on_submit():
        factura = Facturas()
        factura.fecha = datetime.now()
        db.session.add(factura)
        db.session.commit()
        for i in range(5):
            productoInput = request.form.get(f'producto{i}')
            cantidadInput = request.form.get(f'cantidad{i}', type=int)
            producto = Productos.query.filter_by(nameProduct=productoInput).first()
            if producto:
                if producto.stock >= cantidadInput and producto.state == True:
                    producto.stock -= cantidadInput
                    db.session.commit()
                    factura_producto = FacturasProductos(idFactura=factura.idFactura, idProducto=producto.idProducto, cantidad=cantidadInput, preu=producto.price)
                    db.session.add(factura_producto)
                else:
                    print('No hay suficiente stock de', productoInput)
                    flash(f'El producto {productoInput} no existe', 'error')
            else:
                print('El producto', productoInput, 'no existe')
                # Aquí lanzamos el mensaje de error
                flash(f'El producto {productoInput} no existe', 'error')
        return redirect(request.url)
    else:
        print("Error en el formulario.")
    return render_template("facturas.html", form=form)
@main.route('/update_price/<int:idProducto>', methods=['POST'])
def update_price(idProducto):
    producto = Productos.query.get_or_404(idProducto)
    if request.method == 'POST':
        nuevo_precio = request.form.get('price')
        if nuevo_precio:
            producto.price = nuevo_precio
            db.session.commit()
            return redirect(url_for('main.producto', idProducto=idProducto))
    return redirect(url_for('main.producto', idProducto=idProducto))

@main.route('/toggle_state/<int:idProducto>', methods=['POST'])
def toggle_state(idProducto):
    producto = Productos.query.get_or_404(idProducto)
    producto.state = not producto.state
    db.session.commit()
    flash(f'El estado del producto {producto.nameProduct} ha sido actualizado.', 'success')
    return redirect(url_for('main.producto', idProducto=idProducto))

templates/albaran.html
{% extends 'base.html' %}
{% block title %}
ALBARANES
{% endblock %}

{% block body %}
<h1 class="title">ALBARANES</h1>
<div class="container">
  <form class="albaran-form" method="POST">
    {{ form.hidden_tag() }}
    {% for i in range(5) %}
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="producto{{ i }}">Producto:</label>
        {{ form['producto' + i|string]() }}
        {% for error in form['producto' + i|string].errors %}
        <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="col-md-6">
        <label for="cantidad{{ i }}">Cantidad:</label>
        {{ form['cantidad' + i|string]() }}
        {% for error in form['cantidad' + i|string].errors %}
        <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <label for="proveedor">Proveedor:</label>
    {{ form.proveedor() }}
    <br>
    <input type="submit" value="Enviar Productos" />
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='form.css') }}">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous" 
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body style="background-color: ivory;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">FLASK APP</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/productos">PRODUCTOS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/albaranes">ALBARANES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/facturas">FACTURAS</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>

    {% block body %} {% endblock %}
  </body>
</html>

templates/facturas.html
{% extends 'base.html' %}
{% block title %}
FACTURAS
{% endblock %}

{% block body %}
<h1 class="title">FACTURAS</h1>

{% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

<div class="container">
  <form class="albaran-form" method="POST">
    {{ form.hidden_tag() }}
    {% for i in range(5) %}
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="producto{{ i }}">Producto:</label>
        {{ form['producto' + i|string]() }}
        {% for error in form['producto' + i|string].errors %}
        <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="col-md-6">
        <label for="cantidad{{ i }}">Cantidad:</label>
        {{ form['cantidad' + i|string]() }}
        {% for error in form['cantidad' + i|string].errors %}
        <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    <input type="submit" value="Enviar Productos" />
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
Index
{% endblock %}

{% block body %}
<h1 style="text-align: center; margin-top: 30px;">CICLO DE VIDA DE UN PRODUCTO</h1>
{% endblock %}

templates/producto.html
{% extends 'base.html' %}

{% block title %}
{{ producto.nameProduct }}
{% endblock %}

{% block body %}
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <ul class="list-group text-center">
        <li class="list-group-item">{{ producto.nameProduct }}</li>
        {% if producto.price is none %}
        <li class="list-group-item">
          <form method="POST" action="{{ url_for('main.update_price', idProducto=producto.idProducto) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-group">
              <label for="price">Añadir Precio:</label>
              <input type="number" class="form-control" id="price" name="price" step="0.01" required>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Guardar</button>
          </form>
        </li>
        {% else %}
        <li class="list-group-item">{{ producto.price }}$</li>
        {% endif %}
        <li class="list-group-item">Stock: {{ producto.stock }}</li>
        <li class="list-group-item">Estado: {{ "Activo" if producto.state else "Inactivo" }}</li>
        <li class="list-group-item">
          <form method="POST" action="{{ url_for('main.toggle_state', idProducto=producto.idProducto) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-warning mt-2">{{ "Desactivar" if producto.state else "Activar" }}</button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/productos.html
{% extends 'base.html' %}

{% block title %}
Productos
{% endblock %}

{% block body %}
<h1 style="text-align: center; margin-top: 40px;">PRODUCTOS</h1>
<div class="container">
    <div class="row">
        {% for producto in productos %}
        <div class="col-md-4 mb-4 d-flex align-items-stretch">
            <div class="card" style="width: 18rem; margin: 0 25px;">
                <div class="card-body">
                    <h5 class="card-title">{{ producto.nameProduct }}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{ producto.price }}$</h6>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Stock: {{ producto.stock }}</h6>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Estado: {{ "Activo" if producto.state else "Inactivo" }}</h6>
                    <a href="{{ url_for('main.ver_mas', idProducto=producto.idProducto) }}" class="card-link">Ver más</a>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-12">
            <p>No hay productos</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}